# -*- coding: utf-8 -*-
"""Untitled12.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9yTOj4jQ7dYqVQ1QJ6tPlsu2rqI0XTq
"""

def get_divisors(number):
    divisors = []
    for i in range(1, number + 1):
        if number % i == 0:
            divisors.append(i)
    return divisors

# 테스트할 숫자 직접 지정
number = 12  # 여기서 숫자를 원하는 값으로 변경하세요
print("Divisors of", number, "are:", get_divisors(number))